### ISSUE TITLE
this PNG image crashes application when loading

### ISSUE THREAD

**Issue by Agamnentzar** [Automattic/node-canvas#1612]
## Issue or Feature

node process is crashing with following message

```
Exception code=0xc0000005 flags=0x0 at 0x00007FFB878A7DD0. Access violation - attempting to read data at address 0x0000024B46E5D000
```

image in question:

![fail](https://user-images.githubusercontent.com/572298/85976374-b93ccc80-b9da-11ea-9dd4-f579a6e4724f.PNG)

## Steps to Reproduce

```js
var Canvas = require('canvas');
Canvas.loadImage('fail.PNG').then(canvas => console.log(canvas));
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): v13.14.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Windows 10

**Comment by zbjornson** [comment]
That PNG is corrupt (missing iEND, bad chunk length), but ideally that error would be handled. This looks like a cairo bug. The only open related issue I see is this, which is not quite the same: https://gitlab.freedesktop.org/cairo/cairo/-/issues/254. Fixing this would likely be time-consuming, and rather than fix bugs in current node-canvas I'm hoping to spend more time on a brand new implementation, which should fix this problem as well. Happy to review a PR if anyone wants to work on it though.

**Comment by Agamnentzar** [comment]
It seems to be libpng bug, updating to latest libpng solves the crashing but still doesn't load the PNG, I don't know if it can be updated independent of cairo though.

**Comment by pranavburnwal** [comment]
+1
