### ISSUE TITLE
Expression: object->InternalFieldCount() > 0

### ISSUE THREAD

**Issue by svantonov** [Automattic/node-canvas#855]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = new Canvas(200, 200);
...
```

## Error
Assertion failed!

Program: ...\node_modules\canvas\build\Release\canvas.node
File: ...\node_modules\nan\nan_object_wrap.h

Expression: object->InternalFieldCount() > 0
....

## Your Environment
* Version of node-canvas (e.g. v1.6.2):
* Environment (e.g. node v6.9.1 (x64) on Windows 10):

**Comment by zbjornson** [comment]
This is fixed by #808 :-)

**Comment by svantonov** [comment]
I used installing instructions for Windows and nothing changed in node-canvas code.
Node installer download from official website.
Is fix already applied to v1.6.2 release?

**Comment by zbjornson** [comment]
Ah, sorry for not being clear. #808 is not merged into master yet.

The other people who have reported this problem only got the assertion failure while a debugger was attached. If you need an immediate fix, you could use the branch for #808 (`npm install github:zbjornson/node-canvas#prototype-fix`), or try not using a debugger if you're using one...

**Comment by svantonov** [comment]
Thank you. But this fix just halt application (in debug mode) without any message.
I used debug mode with Visual Studio Code.
Application works without debug.

**Comment by zbjornson** [comment]
OK, I can reproduce that with Visual Studio Code in both launch and attach modes if I put a breakpoint after your 1st line (procdump says 0xc0000005, access violation), but I cannot reproduce it with Visual Studio or with the node.js built-in debugger.

I don't know how VSCode's debugger works with node to try to troubleshoot this further, unfortunately. I can't tell if this is from node-canvas or vscode, but it's odd that it only happens wtih vscode's debugger.

**Comment by ip** [comment]
I'm experiencing the same problem:

![image](https://user-images.githubusercontent.com/1111008/28565195-90abc206-713c-11e7-9c1c-f17b40da029e.png)

It crashes on the line with `new Canvas(...)`

**Comment by zbjornson** [comment]
Oops, I had a typo in PR #808 -- it should have said "Fixes #855" (this issue). This is fixed in 2.0-alpha.

**Comment by webworker01** [comment]
Hello I am receiving this error on 2.0-alpha

**Comment by zbjornson** [comment]
@webworker01 is there a particular line of your code that causes it to happen?

**Comment by feuerste** [comment]
@zbjornson would it be a lot of effort to backport PR #808 into the 1.x series?

**Comment by RedGlow** [comment]
I still get this bug with 1.6.11 under Windows with debugger attached.

**Comment by zbjornson** [comment]
@RedGlow this is fixed in 2.x. I don't have plans at the moment to backport it to 1.x, as I think/hope 2.x will be out of alpha shortly.

I left this open because @webworker01 reported a crash in 2.0.0-alpha.5, but I haven't heard back, so will close now.
